### ISSUE TITLE
Rubric and Summary

### ISSUE THREAD

**Issue by ulisigi** [prproksch/Colmar-Acedemy-Codecademy#4]
### Criteria 1: HTML Structure  
* _Score Level:_ 4/4
* _Comment(s):_ HTML implementation enables proper use of media queries.
HTML structure reflects the grouping and flow of content in the web browser
 
### Criteria 2: Visual Layout for Both Desktop and Mobile Sizes
* _Score Level:_ 3/4
* _Comment(s):_ Desktop OR mobile layout match the wireframe in all sections.
 
### Criteria 3: Responsive Design (Media Queries, Responsive Units, etc.)
* _Score Level:_ 4/4
* _Comment(s):_ Media queries kick in at appropriate breakpoints. 
Responsive units are used throughou
 
### Criteria 4: Visual Design and Accessibility (Color Palette, Typography, Transitions, etc.)
* _Score Level:_ 4/4
* _Comment(s):_ An accessible color palette was chosen. Typographic considerations were made. CSS transitions were used.

 
### Overall Score: 15/16
Great work overall on this project! Good use of semantic elements in your HTML, and comments in the HTML and CSS to help keep your code readable. Your project was missing a reset.css stylesheet. While not explicitly required, it can help your page display more predictably across different browsers by removing many defaults before your style.css sheet is applied to your content. Keep experimenting with design choices and seek feedback from other learners and moderators of your course. Keep up the great work, and happy coding!

**Comment by prproksch** [comment]
Thank you very much for your review! :D
